import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Pages as data } from "@/data/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2 justify-center items-center">
          {data.map((page, index) => (
            <Link key={index} href={page.url}>
              <span className="border-2 border-black px-2"> {page.title}</span>
            </Link>
          ))}
        </div>
        {children}
      </body>
    </html>
  );
}
